language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer require satooshi/php-coveralls:dev-master
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
